<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "qbcontact"
 *
 * Auto generated by Extension Builder 2013-11-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'qbMaps: Display Google maps',
	'description' => 'Several ways to display maps and markers on it',
	'category' => 'plugin',
	'author' => 'Axel Wüstemann',
	'author_email' => 'awu@qbus.de',
	'author_company' => 'Qbus Werbeagentur GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.1',
			'fluid' => '6.1',
			'typo3' => '6.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
